//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public long idRegistro { get; set; }
        public string DetalleError { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
