//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.MaterialesTrabajo = new HashSet<MaterialesTrabajo>();
        }
    
        public int idProducto { get; set; }
        public int idProveedor { get; set; }
        public string nombre { get; set; }
        public string marca { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string precio { get; set; }
        public Nullable<int> idCuenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialesTrabajo> MaterialesTrabajo { get; set; }
        public virtual Historico Historico { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
