//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalCore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajo()
        {
            this.MaterialesTrabajo = new HashSet<MaterialesTrabajo>();
        }
    
        public int idTrabajo { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idEstadoTrabajo { get; set; }
        public string descripcion { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string nombreCliente { get; set; }
        public string telefonoCliente { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual EstadoTrabajo EstadoTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialesTrabajo> MaterialesTrabajo { get; set; }
    }
}
